# Generated by Django 4.2.3 on 2023-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_floorimage_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='floorimage',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='floorimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
